# This is a basic workflow to help you get started with Actions

name: Build and Test/analysis then Upload to GAR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build application
        run: |
          echo "Building.."
          sleep 60
          echo "Building done"
          echo "This is contents of build artifact" > artifact.war
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: artifact.war
  upload:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
      - name: Upload to GAR
        run: |
          ls -l
          echo "Uploading to GAR.."
          sleep 10
          echo "Uploading to GAR done"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Unit test
        run: |
          echo "Running unit tests.."
          sleep 10
          echo "Running unit tests done"
      - name: Static Analysis
        run: |
          echo "Running static analysis.."
          sleep 10
          echo "Running static analysis done"
