name: "Fast Fail Parallel Job Workaround"

on:
  workflow_dispatch:

jobs:
  fastfailwa:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        jobs: [build_upload_job, test_job]
    steps:
      - name: build_upload_step_1
        if: ${{ matrix.jobs == 'build_upload_job' }}
        run: |
          echo "Building.."
          sleep 60
          echo "Building done"

      - name: build_upload_step_2
        if: ${{ matrix.jobs == 'build_upload_job' }}
        run: |
          echo "Uploading to GAR.."
          sleep 10
          echo "Uploading done"

      - name: test_step_1
        if: ${{ matrix.jobs == 'test_job' }}
        run: |
          echo "Running unit tests.."
          sleep 60
          exit -1
          echo "Running unit tests done"

      - name: test_step_2
        if: ${{ matrix.jobs == 'test_job' }}
        run: |
          echo "Running static analysis.."
          sleep 60
          echo "Running static analysis done"
